<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SanPhamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        DB::table('sanpham')->insert([
            [
                'ten' => 'Kem chong nang',
                'mota' => 'chong nang',
                "gia" => "500000",
                "sale" => "35000",
                "hinh" => "hinh1.jpg",
                "soluongtrongkho" => "2000",
                "soluongdaban" => "20",
                "danhmucsp_id" => "1",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Nuoc tay trang',
                'mota' => 'dùng cho da bình thường, da dầu,da khô,.... ',
                "gia" => "200000",
                "sale" => "75000",
                "hinh" => "hinh2.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "1",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Son dưỡng môi',
                'mota' => 'dùng để cho môi mềm mịn, ko nứt nẻ,....',
                "gia" => "90000",
                "sale" => "25000",
                "hinh" => "hinh3.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "1",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Kem nền',
                'mota' => ' kem nền là làm đều màu da, che đi các khuyết điểm, làm mờ nếp nhăn và tạo cảm giác mịn màng cho làn da,....',
                "gia" => "100000",
                "sale" => "19000",
                "hinh" => "hinh4.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "2",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Kem ủ tóc',
                'mota' => 'Kem ủ tóc là một loại sản phẩm chăm sóc tóc được thiết kế để cung cấp dưỡng chất, độ ẩm và dưỡng ẩm sâu cho tóc... ',
                "gia" => "200000",
                "sale" => "89000",
                "hinh" => "hinh5.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "3",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Son dior',
                'mota' => 'son Dior mang đến không chỉ là một màu sắc tuyệt đẹp mà còn là sự chăm sóc và bảo vệ cho làn môi.',
                "gia" => "500000",
                "sale" => "99000",
                "hinh" => "hinh6.jpg",
                "soluongtrongkho" => "2000000",
                "soluongdaban" => "5000",
                "danhmucsp_id" => "2",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Dầu dưỡng tóc',
                'mota' => 'Dùng để nuôi dưỡng tóc từ bên trong, làm mềm mại, chống gãy rụng và tăng cường sự mềm mại..... ',
                "gia" => "200000",
                "sale" => "75000",
                "hinh" => "hinh7.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "3",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Nước hoa (Perfume)',
                'mota' => 'Là dạng hương thơm có độ nồng độ cao nhất, thường từ 15-30%, giữ hương lâu nhất trên da....                ...',
                "gia" => "80000",
                "sale" => "25000",
                "hinh" => "hinh8.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "4",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Dầu thơm (Perfumed Oil)',
                'mota' => ' Dạng hương thơm dễ thấm vào da, giúp hương thơm lan tỏa dài lâu....',
                "gia" => "100000",
                "sale" => "29000",
                "hinh" => "hinh9.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "4",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Nến thơm (Scented Candles)',
                'mota' => 'Cung cấp không gian ấm áp và thư giãn với hương thơm dễ chịu, thích hợp cho việc tạo không gian thư giãn trong nhà... ',
                "gia" => "200000",
                "sale" => "69000",
                "hinh" => "hinh10.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "4",
                "created_at" => now(),
                "updated_at" => now(),
            ],

            [
                'ten' => 'Sữa rửa mặt',
                'mota' => ' Sữa rửa mặt là sản phẩm giúp làm sạch bụi bẩn, dầu thừa và tạp chất trên da mặt một cách nhẹ nhàng. Sản phẩm này giúp da mặt sảng khoái, sạch sẽ và cân bằng độ pH tự nhiên của da.',
                "gia" => "100000",
                "sale" => "59000",
                "hinh" => "hinh11.jpg",
                "soluongtrongkho" => "200000",
                "soluongdaban" => "200",
                "danhmucsp_id" => "1",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Serum dưỡng da:',
                'mota' => 'Serum dưỡng da là sản phẩm chứa các thành phần dưỡng chất có nồng độ cao, được thiết kế để thẩm thấu sâu vào da, giúp cải thiện tình trạng da như nếp nhăn, sạm da, mụn và tăng cường độ đàn hồi của da. ',
                "gia" => "200000",
                "sale" => "65000",
                "hinh" => "hinh12.jpg",
                "soluongtrongkho" => "9000000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "1",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Mặt nạ dưỡng da ',
                'mota' => ' Mặt nạ dưỡng da là sản phẩm chăm sóc da nhanh chóng và hiệu quả.',
                "gia" => "280000",
                "sale" => "45000",
                "hinh" => "hinh13.jpg",
                "soluongtrongkho" => "5000000",
                "soluongdaban" => "10000",
                "danhmucsp_id" => "3",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Phấn phủ (Setting Powder)',
                'mota' => 'Phấn phủ giúp cố định lớp trang điểm, kiểm soát dầu nhờn và giữ lớp trang điểm không bị trôi trong suốt thời gian dài. Có thể dùng phấn phủ sau khi sử dụng kem nền và các sản phẩm trang điểm khác.',
                "gia" => "100000",
                "sale" => "29000",
                "hinh" => "hinh14.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "2",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Phấn má (Blush):',
                'mota' => ' Phấn má là sản phẩm tạo điểm nhấn cho gò má, tạo sự tươi tắn và sức sống cho khuôn mặt.',
                "gia" => "200000",
                "sale" => "49000",
                "hinh" => "hinh15.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "2",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Highlighte',
                'mota' => 'Highlighter là sản phẩm giúp tạo điểm nhấn sáng và tạo hiệu ứng bóng loáng',
                "gia" => "100000",
                "sale" => "49000",
                "hinh" => "hinh16.jpg",
                "soluongtrongkho" => "2000000",
                "soluongdaban" => "5000",
                "danhmucsp_id" => "2",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Bột tạo khối (Contour Powder)',
                'mota' => 'Dùng để nuôi dưỡng tóc từ bên trong, làm mềm mại, chống gãy rụng và tăng cường sự mềm mại..... ',
                "gia" => "200000",
                "sale" => "75000",
                "hinh" => "hinh17.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "3",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Nước hoa (Perfume)',
                'mota' => ' Bột tạo khối giúp tạo chiều sâu và định hình khuôn mặt ',
                "gia" => "70000",
                "sale" => "35000",
                "hinh" => "hinh18.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "2",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Nước hoa nữ Sweet Blossom',
                'mota' => 'Một hương thơm nữ tính và dịu dàng với hương hoa ngọt ngào',
                "gia" => "100000",
                "sale" => "29000",
                "hinh" => "hinh19.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "4",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'ten' => 'Tinh dầu hương Vanilla',
                'mota' => ' Hương thơm ngọt ngào và ấm áp của vani, tạo cảm giác dịu dàng và ấm cúng',
                "gia" => "200000",
                "sale" => "59000",
                "hinh" => "hinh20.jpg",
                "soluongtrongkho" => "50000",
                "soluongdaban" => "500",
                "danhmucsp_id" => "4",
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
